name: Terraform Apply

on:
  push:
    branches:
      - main
    #paths:
    #  - "outputs.yaml"   # only run if outputs.yaml changes

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write  # required if you use OIDC with GCP
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      # Authenticate to Google Cloud (prefer OIDC over PAT/keys)
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_TERRAFORM_SA }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Terraform Init
        run: terraform init -input=false

      - name: Import VPC-SC
        run: terraform import google_access_context_manager_service_perimeter.my_perimeter "accessPolicies/299155975207/servicePerimeters/my_perimeter"


      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false